config/routes.rb
Rails.application.routes.draw do
  resources :inventory_items

end

app/models/inventory_item.rb
class InventoryItem
  include Mongoid::Document
  field :part_name, type: String
  field :failure_mode, type: String
  field :severity, type: Integer
  field :current_control_defective, type: String
  field :current_control_preventive, type: String
  field :recommended_action, type: String
  field :spare_id, type: Integer
  has_many :spares
  validates_presence_of :spare_id
end

app/models/spare.rb
class Spare
  include Mongoid::Document
  field :stock, type: Integer
  field :name, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: 'Inventory item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_item_params
      params.require(:inventory_item).permit(:part_name, :failure_mode, :severity, :current_control_defective, :current_control_preventive, :recommended_action)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for(@inventory_item) do |f| %>
  <% if @inventory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
      <% @inventory_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :part_name %><br>
    <%= f.text_field :part_name %>
  </div>
  <div class="field">
    <%= f.label :failure_mode %><br>
    <%= f.text_field :failure_mode %>
  </div>
  <div class="field">
    <%= f.label :severity %><br>
    <%= f.number_field :severity %>
  </div>
  <div class="field">
    <%= f.label :current_control_defective %><br>
    <%= f.text_field :current_control_defective %>
  </div>
  <div class="field">
    <%= f.label :current_control_preventive %><br>
    <%= f.text_field :current_control_preventive %>
  </div>
  <div class="field">
    <%= f.label :recommended_action %><br>
    <%= f.text_field :recommended_action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Editing Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_item %> |
<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventory Items</h1>

<table>
  <thead>
    <tr>
      <th>Part name</th>
      <th>Failure mode</th>
      <th>Severity</th>
      <th>Current control defective</th>
      <th>Current control preventive</th>
      <th>Recommended action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_items.each do |inventory_item| %>
      <tr>
        <td><%= inventory_item.part_name %></td>
        <td><%= inventory_item.failure_mode %></td>
        <td><%= inventory_item.severity %></td>
        <td><%= inventory_item.current_control_defective %></td>
        <td><%= inventory_item.current_control_preventive %></td>
        <td><%= inventory_item.recommended_action %></td>
        <td><%= link_to 'Show', inventory_item %></td>
        <td><%= link_to 'Edit', edit_inventory_item_path(inventory_item) %></td>
        <td><%= link_to 'Destroy', inventory_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory item', new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>New Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part name:</strong>
  <%= @inventory_item.part_name %>
</p>

<p>
  <strong>Failure mode:</strong>
  <%= @inventory_item.failure_mode %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @inventory_item.severity %>
</p>

<p>
  <strong>Current control defective:</strong>
  <%= @inventory_item.current_control_defective %>
</p>

<p>
  <strong>Current control preventive:</strong>
  <%= @inventory_item.current_control_preventive %>
</p>

<p>
  <strong>Recommended action:</strong>
  <%= @inventory_item.recommended_action %>
</p>

<%= link_to 'Edit', edit_inventory_item_path(@inventory_item) %> |
<%= link_to 'Back', inventory_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MilDataMongodb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>